[env]
term = "xterm-256color"

[font]
size = 12

[font.normal]
family = "scientifica"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
dynamic_padding = true

[window.padding]
x = 5
y = 7

[terminal]
shell = "fish"
